post:
  tags:
  - Action
  summary: Create action
  description: Create action
  produces:
  - application/json
  parameters:
  - name: X-Request-Id
    in: header
    description: Correlation ID
    required: false
    type: string
    default: goals-test-swagger
  - name: Authorization
    in: header
    description: Auth token
    required: false
    type: string
    default: Basic YWRwOmFkbWlucGFzcw==
  - name: body
    description: Fields for the action to be inserted
    in: body
    required: true
    schema:
      "$ref": "#/definitions/Action"
get:
  tags:
  - Action
  summary: Actions Definitions
  description: Retrieves the complete list of action definitions
  produces:
  - application/json
  parameters:
  - name: X-Request-Id
    in: header
    description: Correlation ID
    required: false
    type: string
    default: goals-test-swagger
  - name: Authorization
    in: header
    description: Auth token
    required: false
    type: string
    default: Basic YWRwOmFkbWlucGFzcw==
  - name: scenarioId
    in: query
    required: true
    type: integer
  responses:
    '200':
      description: list of action definitions (AKA Strategies)
      schema:
        "$ref": "#/definitions/ActionDefinitionsList"
