swagger: '2.0'
info:
  $ref: ./src/info/index.yaml
basePath: /api
tags:
  $ref: ./src/tags/index.yaml
schemes:
- http
- https
paths:
  $ref: ./src/paths/index.yaml
definitions:
  $ref: ./src/definitions/index.yaml
responses:
  $ref: ./src/responses/index.yaml
